import { type SQL, sql } from 'drizzle-orm';
import { bigint, char, check, customType, timestamp, uuid } from 'drizzle-orm/pg-core';
import { uuidv7 } from '../../ids.js';

/** Case-insensitive text (PostgreSQL `citext` extension). */
export const citext = customType<{ data: string; driverData: string }>({
  dataType: () => 'citext',
});

/** UUIDv7 primary key generated by the application; `gen_random_uuid()` for manual SQL. */
export const primaryId = () =>
  uuid()
    .primaryKey()
    .defaultRandom()
    .$defaultFn(() => uuidv7());

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
export const updatedAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
export const timestamptz = () => timestamp({ withTimezone: true });

/** Money in minor units (kuruş, cents). Always paired with a currency column. */
export const minor = () => bigint({ mode: 'number' });
export const currencyCode = () => char({ length: 3 });

function quoteList(values: readonly string[]): string {
  return values.map((value) => `'${value.replaceAll("'", "''")}'`).join(', ');
}

/** CHECK constraint restricting a text column to a fixed set of values. */
export function enumCheck(
  name: string,
  column: string,
  values: readonly string[],
  options: { nullable?: boolean } = {},
) {
  const inList = `"${column}" IN (${quoteList(values)})`;
  const expression: SQL = sql.raw(options.nullable ? `("${column}" IS NULL OR ${inList})` : inList);
  return check(name, expression);
}

export function currencyCheck(name: string, column = 'currency') {
  return check(name, sql.raw(`"${column}" ~ '^[A-Z]{3}$'`));
}
